ssh_ps53: 'yes'
ssh_ps59: 'sandbox'

macs_53_default: 'hmac-ripemd160,hmac-sha1'
macs_59_default: 'hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
macs_59_weak: '{{macs_59_default + ",hmac-sha1"}}'
macs_66_default: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
macs_66_weak: '{{macs_66_default + ",hmac-sha1"}}'

ciphers_53_default: 'aes256-ctr,aes192-ctr,aes128-ctr'
ciphers_53_weak: '{{ciphers_53_default + ",aes256-cbc,aes192-cbc,aes128-cbc"}}'

ciphers_66_default: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
ciphers_66_weak: '{{ciphers_66_default + ",aes256-cbc,aes192-cbc,aes128-cbc"}}'

kex_59_default: 'diffie-hellman-group-exchange-sha256'
kex_59_weak: '{{kex_59_default + ",diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"}}'
kex_66_default: 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
kex_66_weak: '{{kex_66_default + ",diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"}}'

# directory where to store ssh_password policy
custom_selinux_dir: '/etc/selinux/local-policies'
