---
# defaults file for nginx-hardening
client_header_buffer_size: 1k

large_client_header_buffers: 2 1k

client_body_timeout: 10

client_header_timeout: 10

send_timeout: 10

limit_conn_zone: $binary_remote_addr zone=default:10m
limit_conn: default 50